services:
    simplifiedcleanarchmodel.api:
        image: ${DOCKER_REGISTRY-}simplifiedcleanarchmodelapi
        build:
            context: .
            dockerfile: SimplifiedCleanArchModel.Api/Dockerfile
        ports:
            - "8080:8080"
        environment:
            - ASPNETCORE_URLS=http://+:8080
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CleanArchDb;User=user;Password=Pass@123;
        depends_on:
            - sqlserver
        networks:
            - myapp-net
        volumes:
            - .:/app

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Pass@123
        networks:
            - myapp-net
        volumes:
            - sqlserver-data:/var/opt/mssql

networks:
  myapp-net:

volumes:
  sqlserver-data: